import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { logger } from '@/lib/logger';
import { toast } from '@/components/ui/use-toast';

export interface Ticket {
  id: string;
  ticket_number: string;
  subject: string;
  description: string | null;
  user_id: string | null;
  user_email: string;
  user_name: string | null;
  status: string;
  priority: string;
  category: string | null;
  assigned_to: string | null;
  resolved_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface TicketMessage {
  id: string;
  ticket_id: string;
  sender_id: string | null;
  sender_type: string;
  message: string;
  created_at: string;
  profiles?: { full_name: string | null } | null;
}

export function useTickets() {
  const [tickets, setTickets] = useState<Ticket[]>([]);
  const [loading, setLoading] = useState(true);
  const [userId, setUserId] = useState<string | null>(null);

  useEffect(() => {
    const { data: { subscription } } = supabase.auth.onAuthStateChange(
      (_event, session) => {
        setUserId(session?.user?.id ?? null);
      }
    );

    supabase.auth.getSession().then(({ data: { session } }) => {
      setUserId(session?.user?.id ?? null);
    });

    return () => subscription.unsubscribe();
  }, []);

  const fetchTickets = useCallback(async () => {
    if (!userId) return;

    try {
      setLoading(true);
      const { data, error } = await supabase
        .from('support_tickets')
        .select('*')
        .eq('user_id', userId)
        .order('created_at', { ascending: false });

      if (error) throw error;
      setTickets((data as Ticket[]) || []);
    } catch (error) {
      logger.error('Error fetching tickets:', error);
      toast({
        title: 'Erro',
        description: 'Falha ao carregar seus tickets de suporte.',
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  }, [userId]);

  useEffect(() => {
    if (userId) fetchTickets();
  }, [userId, fetchTickets]);

  const createTicket = async (subject: string, description: string, category: string = 'general') => {
    if (!userId) return null;

    try {
      const { data: profile } = await supabase
        .from('profiles')
        .select('full_name, email')
        .eq('id', userId)
        .single();

      const { data, error } = await supabase
        .from('support_tickets')
        .insert({
          subject,
          description,
          category,
          user_id: userId,
          user_email: profile?.email || '',
          user_name: profile?.full_name || '',
          ticket_number: '', // auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;

      // Add the description as the first message
      if (data) {
        await supabase
          .from('support_ticket_messages')
          .insert({
            ticket_id: data.id,
            sender_id: userId,
            sender_type: 'customer',
            message: description,
          });
      }

      toast({
        title: 'Ticket criado',
        description: 'Seu ticket de suporte foi criado com sucesso.',
      });

      await fetchTickets();
      return data as Ticket;
    } catch (error) {
      logger.error('Error creating ticket:', error);
      toast({
        title: 'Erro',
        description: 'Falha ao criar ticket de suporte.',
        variant: 'destructive',
      });
      return null;
    }
  };

  const getTicketMessages = async (ticketId: string): Promise<TicketMessage[]> => {
    try {
      const { data, error } = await supabase
        .from('support_ticket_messages')
        .select('*, profiles(full_name)')
        .eq('ticket_id', ticketId)
        .order('created_at', { ascending: true });

      if (error) throw error;
      return (data as TicketMessage[]) || [];
    } catch (error) {
      logger.error('Error fetching ticket messages:', error);
      return [];
    }
  };

  const sendMessage = async (ticketId: string, message: string) => {
    if (!userId) return false;

    try {
      const { error } = await supabase
        .from('support_ticket_messages')
        .insert({
          ticket_id: ticketId,
          sender_id: userId,
          sender_type: 'customer',
          message,
        });

      if (error) throw error;

      // Update ticket updated_at by touching the ticket
      await supabase
        .from('support_tickets')
        .update({ updated_at: new Date().toISOString() })
        .eq('id', ticketId);

      return true;
    } catch (error) {
      logger.error('Error sending message:', error);
      toast({
        title: 'Erro',
        description: 'Falha ao enviar mensagem.',
        variant: 'destructive',
      });
      return false;
    }
  };

  return {
    tickets,
    loading,
    fetchTickets,
    createTicket,
    getTicketMessages,
    sendMessage,
  };
}
